<a href="https://colab.research.google.com/github/sbj6364/python-practice/blob/main/numpy-basic/10_fancy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10번 : fancy indexing


주어진 2차원 numpy array는 행렬을 나타냅니다.  
주어진 행렬에서 첫번째 행과, 두번째 열을 출력하는 코드를 작성해보세요.
  
#### 베이스라인
~~~python
arr2 = np.array([ [10, 9, 8], [7, 6, 5], [4, 3, 2] ])

'''
code here
'''
~~~
#### Output
~~~
array([10, 9, 8])
array([9, 6, 3])
~~~


In [24]:
import numpy as np
arr2 = np.array([[10, 9, 8], [7, 6, 5], [4, 3, 2]])

print(arr2[0,:])
print(arr2[:,1])

[10  9  8]
[9 6 3]
