<a href="https://colab.research.google.com/github/sbj6364/python-practice/blob/main/numpy-basic/11_array_masking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11번 : array masking


주어진 numpy array 에 대해서, 30보다 큰 숫자만 뽑는 코드를 작성하세요.  
(단, 반복문을 통한 방법이 아닌 numpy array masking을 사용하세요.)
  
#### 베이스라인
~~~python
arr = np.array([30, 4, 550, 9, 112, 10000, 15, 21])

'''
code here
'''
~~~
#### Output
~~~
array([550, 112, 10000])
~~~



In [9]:
import numpy as np
import numpy.ma as ma
arr = np.array([30, 4, 550, 9, 112, 10000, 15, 21])

print(arr[ma.greater(arr, 30)==True])
print(arr[arr>30])

[  550   112 10000]
[  550   112 10000]
